# Generated by Django 4.1.3 on 2024-03-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.TextField(verbose_name='Interests')),
                ('past_experience', models.TextField(verbose_name='Past Experiences')),
                ('upcoming', models.TextField(verbose_name='Upcoming')),
            ],
        ),
    ]
